### ISSUE TITLE
Identical USB adapters not seen when trying to list ports

### ISSUE THREAD

**Issue by bigmonkeyboy** [voodootikigod/node-serialport#329]
On Linux (Ubuntu) the listUnix call in serialport.js uses /dev/serial/by-id.
If I have two identical USB serial adaptors plugged in next to each other they end up with the same id - so don't get reported back correctly 
eg by-path shows 2 adaptors, while by-id only shows 1

ls -r /dev/serial/*
by-path:
pci-0000:0e:00.0-usb-0:2:1.0-port0  pci-0000:0e:00.0-usb-0:1:1.0-port0

by-id:
usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0

I just tried changing all refs of by-id to by-path and it all seems to work correctly...

**Comment by jacobrosenthal** [comment]
Tracking this here https://github.com/voodootikigod/node-serialport/issues/610
