### ISSUE TITLE
node-serialport install if nw-gyp is installed

### ISSUE THREAD

**Issue by voodootikigod** [voodootikigod/node-serialport#383]
This ticket is to consolidate all issues relating to attempting to install node-serialport when [nw-gyp](https://www.npmjs.org/package/nw-gyp) is installed. If you are redirect to here from a different ticket is to help isolate and reduce the number of duplicates with this as the core issue. Please review this ticket for information about how to make it work.

**Comment by sdaitzman** [comment]
I've got the same issue. It looks like nw is looking for a version build specifically for it.

**Comment by voodootikigod** [comment]
Sample code would be great

On Saturday, May 9, 2015, Sam D <notifications@github.com> wrote:

> I've got the same issue. It looks like nw is looking for a version build
> specifically for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voodootikigod/node-serialport/issues/383#issuecomment-100484528>
> .
>


-- 
*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by voodootikigod** [comment]
This is due to the way nw.js/node-webkit changes the Node-ABI. This is not an issue with serialport, review this for more information: https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons

Closing
