### ISSUE TITLE
Unable to rebuild with node-gyp

### ISSUE THREAD

**Issue by nyxynyx** [voodootikigod/node-serialport#390]
When using a Meteor deployment tool [mup](https://github.com/arunoda/meteor-up) to deploy to an Ubuntu 14.04 x64 server, it throws an error related to `node-serialport`:

        gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

I've traced this down to `node-serialport` (fantastic package!) as there were no problems with other npm packages that also uses `node-gyp` in the deployment process.

Using node v0.10.32 and node-serialport v1.4.6. Also tested to have same problem with node 0.10.31, 0.10.30, 0.10.29, 0.10.28

Here's the stack trace from the tool:

	$ mup deploy

	Meteor Up: Production Quality Meteor Deployments
	------------------------------------------------

	Bundling Started: .

	Started TaskList: Deploy app 'my-test-app' (linux)
	[192.168.1.114] - Uploading bundle
	[192.168.1.114] ✔ Uploading bundle: SUCCESS
	[192.168.1.114] - Setting up Environment Variables
	[192.168.1.114] ✔ Setting up Environment Variables: SUCCESS
	[192.168.1.114] - Invoking deployment process
	[192.168.1.114] ✘ Invoking deployment process: FAILED
		
		-----------------------------------STDERR-----------------------------------
		gyp info spawn args   '-Dmodule_root_dir=/opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport',
		gyp info spawn args   '--depth=.',
		gyp info spawn args   '--no-parallel',
		gyp info spawn args   '--generator-output',
		gyp info spawn args   'build',
		gyp info spawn args   '-Goutput_dir=.' ]
		gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
		gyp ERR! configure error 
		gyp ERR! stack Error: `gyp` failed with exit code: 1
		gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
		gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
		gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
		gyp ERR! System Linux 3.12.28+
		gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
		gyp ERR! cwd /opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport
		gyp ERR! node -v v0.10.32
		gyp ERR! node-gyp -v v1.0.2
		gyp ERR! not ok 
		-----------------------------------STDOUT-----------------------------------
		=> re-installing binary npm module 'serialport' of package 'npm-container'
		----------------------------------------------------------------------------
	Completed TaskList: Deploy app 'my-test-app' (linux)

And the error messages when I run `node-gyp rebuild` in the directory containing `node-serialport`:

	# node-gyp rebuild
	gyp info it worked if it ends with ok
	gyp info using node-gyp@1.0.2
	gyp info using node@0.10.32 | linux | x64
	gyp info spawn python
	gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'make',
	gyp info spawn args   '-I',
	gyp info spawn args   '/opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport/build/config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/root/.node-gyp/0.10.32/common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.32',
	gyp info spawn args   '-Dmodule_root_dir=/opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
	gyp ERR! configure error 
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
	gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
	gyp ERR! System Linux 3.13.0-32-generic
	gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
	gyp ERR! cwd /opt/my-test-app/tmp/bundle/programs/server/npm/npm-container/node_modules/serialport
	gyp ERR! node -v v0.10.32
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok

**Comment by ffissore** [comment]
Confirm: @LukeRiceApperson advice works with node-webkit as well. See https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

**Comment by voodootikigod** [comment]
This is due to the way nw.js/node-webkit changes the Node-ABI. This is not an issue with serialport, review this for more information: https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons

Closing
