### ISSUE TITLE
serialPort.list only shows single most recently connected port

### ISSUE THREAD

**Issue by RIAEvangelist** [voodootikigod/node-serialport#407]
Using ubuntu 14.04 LTS

    serialPort.list(
        function (err, ports) {
            console.log(ports); //this is only logging the single most recently connected serial port.
        }
    );

any ideas?

**Comment by jacobrosenthal** [comment]
Closing as no follow up information, but were working on linux listing here. 
Perhaps these were identical devices? Weve seen that before and are working on it https://github.com/voodootikigod/node-serialport/issues/610
