### ISSUE TITLE
Writing to serial port not working (Windows 7)

### ISSUE THREAD

**Issue by aventuel** [voodootikigod/node-serialport#421]
Hi,
I'm trying to write a character in serial port, but nothing gets Arduino  (Windows 7)

//////////////// node /////////////////////
```js
var sport = require('serialport');

var sp = new sport.SerialPort('COM4', {
baudRate: 9600,
   dataBits: 8, 
   parity: 'none', 
   stopBits: 1, 
}, false, 0);

sp.open(function (error) {
	sp.write("S");
});
```

//////////////// arduino ///////////////////
```js
const int outputPin = 13;
 
void setup()
{
  pinMode(outputPin, OUTPUT);
  Serial.begin(9600);
}
 
void loop()
{
  if (Serial.available() > 0) {
      digitalWrite(outputPin, HIGH);
  }
}
```

Thanks, Stanislav

**Comment by mn1aC** [comment]
How did you solve it?

I'm having the same problem... I'm not able to write a command from to the serial port on a windows machine..

**Comment by aventuel** [comment]
//////////////// node /////////////////////
```js
var readline = require('readline');
var SerialPort = require("serialport").SerialPort;

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

var serialPort = new SerialPort("COM4", {
  baudrate: 9600
});

serialPort.on("open", function () {
	console.log('open');

	serialPort.on('data', function(data) {

		rl.question("input number (0|1)", function(answer) {

			serialPort.write(answer, function(err, results) {
				console.log('send: ' + answer);
			});	
			
		});

	});
});
```

//////////////// arduino  /////////////////////
```js
const int blinkPin = 13;

void setup()
{
	pinMode(blinkPin, OUTPUT);
	Serial.begin(9600);
	Serial.println("");
}

void loop()
{
	if (Serial.available() > 0) {
		int command = Serial.read();

		if (command == 48) {
			digitalWrite(blinkPin, LOW);
			Serial.println(command);
		}

		if (command == 49) {
			digitalWrite(blinkPin, HIGH);
			Serial.println(command);
		}
	}
}
```

**Comment by aventuel** [comment]
To receive and send data to arduino, it is necessary to wait for the COM port is ready. Arduino sends a null string when ready in SETUP function (Serial.println("")). Node receives the first data packet from arduino, and then ready to work to read or write. In this example, you can control the switching of the LED 0 or 1. I hope that helped you. Goodluck

**Comment by Willjobs94** [comment]
I'm actually working with the node serial and i did this using port.open function to open a new connection with the port, rather than port.on("open") event.
