### ISSUE TITLE
Port logging Serial Port via USB with USB expander

### ISSUE THREAD

**Issue by humblewizard** [voodootikigod/node-serialport#460]
Port logging with node > serialport is not picking up all the ports connected through a USB expander. I have a 1:4 USB expander with a Prolific RS232->USB plugged into each USB port. The Linux OS sees all of the ports:

      $ sudo setserial -g /dev/ttyUSB*
      /dev/ttyUSB0, UART: 16654, Port: 0x0000, IRQ: 0
      /dev/ttyUSB1, UART: 16654, Port: 0x0000, IRQ: 0
      /dev/ttyUSB2, UART: 16654, Port: 0x0000, IRQ: 0
      /dev/ttyUSB3, UART: 16654, Port: 0x0000, IRQ: 0
      /dev/ttyUSB4, UART: 16654, Port: 0x0000, IRQ: 0

However the serialport code only sees one of them:

      com.list(function (err, ports){
	   ports.forEach(function(port){
		console.log(port.comName);
		console.log(port.pnpId);
		console.log(port.manufacturer);
	   });
	   console.log("Finished Port Logging\n\n");
      });

The port it sees changes if I move them around on the expander module. This is a bit of a road block for me right now.

**Comment by jacobrosenthal** [comment]
Tracking similar issue at https://github.com/voodootikigod/node-serialport/issues/610
