### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by shenron** [voodootikigod/node-serialport#469]
Hi,

I have:
- Raspberry pi B rev1 (ram 256mo)
- ArchLinux
- Node v0.10.28 (last version arm I found)
- npm 1.4.9

> npm install -g serialport

When I start my script.js

Error: Cannot find module '/usr/lib/node_modules/serialport/build/serialport/v1.5.0/Release/node-v11-linux-arm/serialport.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I don t know how I can resolve this.

**Comment by shenron** [comment]
I use node v0.10.12, with serialport@1.4.0 and now I have these errors:

> serialport@1.4.0 install /opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system (falling back to source compile with node-gyp) 
gyp http GET http://nodejs.org/dist/v0.10.12/node-v0.10.12.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.12/node-v0.10.12.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unexpected eof
gyp ERR! stack     at decorate (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:67:36)
gyp ERR! stack     at Extract.Abstract.error (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:61:12)
gyp ERR! stack     at Extract._streamEnd (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/tar/lib/extract.js:75:22)
gyp ERR! stack     at BlockStream.<anonymous> (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/tar/lib/parse.js:50:8)
gyp ERR! stack     at BlockStream.EventEmitter.emit (events.js:92:17)
gyp ERR! stack     at BlockStream._emitChunk (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/block-stream/block-stream.js:203:10)
gyp ERR! stack     at BlockStream.resume (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
gyp ERR! stack     at Extract.Reader.resume (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/fstream/lib/reader.js:252:34)
gyp ERR! stack     at DirWriter.ondrain (stream.js:61:14)
gyp ERR! stack     at DirWriter.EventEmitter.emit (events.js:92:17)
gyp ERR! System Linux 3.18.8-1-ARCH
gyp ERR! command "/opt/node/node-v0.10.12-linux-arm-pi/bin/node" "/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=serialport" "--configuration=Release" "--module_name=serialport" "--version=1.4.0" "--major=1" "--minor=4" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=./serialport" "--host=https://node-serialport.s3.amazonaws.com/" "--module_path=/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/build/serialport/v1.4.0/Release/node-v11-linux-arm" "--module=/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/build/serialport/v1.4.0/Release/node-v11-linux-arm/serialport.node" "--remote_path=./serialport/v1.4.0/Release/" "--package_name=node-v11-linux-arm.tar.gz" "--staged_tarball=build/stage/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz" "--hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/" "--hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz"
gyp ERR! cwd /opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/node/node-v0.10.12-linux-arm-pi/bin/node /opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.4.0 --major=1 --minor=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/build/serialport/v1.4.0/Release/node-v11-linux-arm --module=/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/build/serialport/v1.4.0/Release/node-v11-linux-arm/serialport.node --remote_path=./serialport/v1.4.0/Release/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.18.8-1-ARCH
node-pre-gyp ERR! command "node" "/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.12
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/opt/node/node-v0.10.12-linux-arm-pi/bin/node /opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.4.0 --major=1 --minor=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/build/serialport/v1.4.0/Release/node-v11-linux-arm --module=/opt/node/node-v0.10.12-linux-arm-pi/lib/node_modules/serialport/build/serialport/v1.4.0/Release/node-v11-linux-arm/serialport.node --remote_path=./serialport/v1.4.0/Release/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.0/Release/node-v11-linux-arm.tar.gz' (1)
npm ERR! weird error 1
npm ERR! not ok code 0


Idea ?

**Comment by shenron** [comment]
I install a fresh Raspbian and I have the same error with the last version of serialport.

**Comment by DrCord** [comment]
I am also having an issue with the latest version of serialport.

**Comment by voodootikigod** [comment]
can someone output the results of 

```
npm info debug
```

**Comment by marcuswinkler** [comment]
Please see also #489. Installing with a version of node older than v0.10.16 will not work.
