### ISSUE TITLE
PR 476 duplicates BREAK functionality from PR 470

### ISSUE THREAD

**Issue by jacobrosenthal** [voodootikigod/node-serialport#479]
Recent PR https://github.com/voodootikigod/node-serialport/pull/476 duplicates existing 
break functionality added https://github.com/voodootikigod/node-serialport/pull/470 and released as 1.6.1

Obviously just an oversight as they landed so close to eachother.

@jerome-42 is there can you test the existing cross platform functionality that now exists in upstream 1.6.1 functionality and ensure that it covers your needs?

**Comment by voodootikigod** [comment]
How do I back this out or finalize a proper conclusion @jacobrosenthal ?

**Comment by jacobrosenthal** [comment]
My suggestion is just that, back out this new commit as it uses a whole new
command path. Rebase or just patch it back out is up to you.

**Comment by jerome-42** [comment]
Sorry for my late response.

I tried set({ brk: true }) with no luck, Cisco router doesn't see break signal.

I think Cisco router is a bit of old school console controller which doesn't see normal break signal. Controller needs a loooooong signal break.

This explain the 1000 parameter, which will be setable from JS code, as delay varies with console speed. 1000 is fine for Cisco router at 9600 baud speed.

**Comment by jacobrosenthal** [comment]
Brk true is infinite break signal if you dont then manually brk false. So
length cant be your issue. Check the example:
https://github.com/voodootikigod/node-serialport/blob/master/examples/break.js

**Comment by jerome-42** [comment]
It works with set({ brk: true }).
Then my code is useless. You can revert the merge.

**Comment by jacobrosenthal** [comment]
Not at all useless I just happened to beat you to the punch this time :)

**Comment by jerome-42** [comment]
No problem :)

**Comment by jacobrosenthal** [comment]
@jerome-42 You could actually do me a huge favor. Im petitioning to get Break functionality into chrome as its not currently supported. If you or any of your other Cisco friends could +1 this ticket that might move it forward:
https://code.google.com/p/chromium/issues/detail?id=461169&q=break&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

**Comment by jerome-42** [comment]
Done :)
