### ISSUE TITLE
[Question] Last step for Windows

### ISSUE THREAD

**Issue by kennethlimcp** [voodootikigod/node-serialport#503]
I'm updating my tutorial and i saw this last line:

```
Open the 'Visual Studio Command Prompt' and add Python to the path.
```

Anyone has some specific instructions on how this can be done? I can test on my Windows VM but thought it might be faster to clarify here instead of doing it wrongly.

Thanks! :)

**Comment by wildeyes** [comment]
I have python on the path environment variable and it installs just fine!

**Comment by kennethlimcp** [comment]
So is the README instructions incorrect or should there be a mentioned for python in PATH?
