### ISSUE TITLE
serialport_unix.cpp compilation shows -Wtautological-pointer-compare warning

### ISSUE THREAD

**Issue by adroit91** [voodootikigod/node-serialport#521]
Hi,

While installing the latest version on my Mac, I saw the following warnings:

npm info install serialport@1.6.3

> serialport@1.6.3 install /usr/local/lib/node_modules/arduino-firmata/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.5.19
node-pre-gyp info using node@0.12.0 | darwin | x64
node-pre-gyp info check checked for "/usr/local/lib/node_modules/arduino-firmata/node_modules/serialport/build/serialport/v1.6.3/Release/node-v14-darwin-x64/serialport.node" (not found)
node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v14-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v14-darwin-x64.tar.gz
node-pre-gyp http Pre-built binary not available for your system (falling back to source compile with node-gyp) 
child_process: customFds option is deprecated, use stdio instead.
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.12.0 | darwin | x64
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/arduino-firmata/node_modules/serialport/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/zepellin/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/zepellin/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/arduino-firmata/node_modules/serialport',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:667:20: warning: comparison of array 'device.locationId' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.locationId != NULL) {
            ~~~~~~~^~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:670:20: warning: comparison of array 'device.vendorId' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.vendorId != NULL) {
            ~~~~~~~^~~~~~~~    ~~~~
../src/serialport_unix.cpp:673:20: warning: comparison of array 'device.productId' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.productId != NULL) {
            ~~~~~~~^~~~~~~~~    ~~~~
../src/serialport_unix.cpp:676:20: warning: comparison of array 'device.manufacturer' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.manufacturer != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:679:20: warning: comparison of array 'device.serialNumber' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.serialNumber != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
5 warnings generated.
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/serialport.node
  SOLINK_MODULE(target) Release/serialport.node: Finished
  COPY /usr/local/lib/node_modules/arduino-firmata/node_modules/serialport/build/serialport/v1.6.3/Release/node-v14-darwin-x64/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp
gyp info ok 
node-pre-gyp info ok 
npm info postinstall serialport@1.6.3

I think it should be easily solvable with a "!==" instead of "!=".

Regards,
Anup

**Comment by jacobrosenthal** [comment]
Fixed in https://github.com/voodootikigod/node-serialport/pull/615
