### ISSUE TITLE
May 2015 update for Raspi/ARM

### ISSUE THREAD

**Issue by figital** [voodootikigod/node-serialport#524]
Seem to have installed node-serialport on a raspi using the 10.28 ARM build ...

http://nodejs.org/dist/v0.10.28/

... looked like the most recent one available for ARM. (the instructions say 10.16)

Something to update in the README.md? A brief explanation that the latest builds aren't available for ARM would be helpful for n00bs.

**Comment by GlennGeenen** [comment]
I just installed v0.12.1 on the Raspberry Pi from http://node-arm.herokuapp.com and everything works fine.

**Comment by figital** [comment]
Good to know ! I'll try that one first next time.

**Comment by jacobrosenthal** [comment]
Closing for #579
