### ISSUE TITLE
output is being truncated when data is received from the serial device

### ISSUE THREAD

**Issue by c0debreaker** [voodootikigod/node-serialport#536]
I'm using minicom and screen utilities to connect to my serial device. I can see the messages being sent by my serial device in single line.

However, when I use SerialPort, the strings are being displayed in multiple lines. Sometimes, my nodejs app will display the output in one line but most of the time, it's displaying it in multiple lines(see screenshot below). The data being sent by the serial device is really short, maybe about 16 characters only. Here is my code

```
serialPort.on("open", function () {
  console.log('open');
  serialPort.on('data', function(data) {
    console.log('data received: ' + data);
  });
});
```

Here is a screenshot while I was running my node application( http://i.imgur.com/Lul3s23.png ). You will see, it's being displayed in multiple lines. If you look at the topmost first few lines, it's displaying it in multiplelines. However, I will only see 16XK5905221310515110006D in one line when I use minicom or screen utility.

Is there something I need to change in my code?

**Comment by c0debreaker** [comment]
It's ok now, I figured out a way to combine them. I used chars 13 & 10 as the terminator.

**Comment by Moussawi7** [comment]
Hi @c0debreaker ,
In fact i encountered exactly the same issue,
where you terminate the string with the characters(13,10) ?.
Thank you.

**Comment by c0debreaker** [comment]
This is how I'm doing it

```
    for (i = 0; i < data.length; i++) {
        if (data[i] != 10 || data[i] != 13) {
          buffer += String.fromCharCode(data[i]);
        }
        if (data[i] == 13) {
            if (buffer.length > 0) {
                //console.log('buffer: '+ buffer.replace(/\n|\r/g, ''));
                reading = buffer.replace(/\n|\r/g, '').toString();
                // All the magic here
		//console.log('reading', reading);
```
