### ISSUE TITLE
Mock a serial port

### ISSUE THREAD

**Issue by cyrilchapon** [voodootikigod/node-serialport#539]
Is there a way to instanciate a **mock** of a serial port ?

I Basically would like to unit-test an higher stack (a serial nmea reader) using node-serialport, without using a physical serial port.

I found [test_mocks/linux_hardware.js](https://github.com/voodootikigod/node-serialport/blob/master/test_mocks/linux-hardware.js) (idea taken from [this post](http://stackoverflow.com/a/28772301/4578952)) but I've not been able to use it.

I couldn't find any example in the *example* directory, neither any documentation about sandboxed and mocked testing on *README.md*

**Comment by voodootikigod** [comment]
https://www.npmjs.com/package/virtual-serialport
