### ISSUE TITLE
multi data received

### ISSUE THREAD

**Issue by masnatacion** [voodootikigod/node-serialport#541]
I created my connection and send data succesfuly but I received the response in multiparts like this:

a0 13 01 89 94 30 00 39 36 30 36
31
37 36 31 35 32 00 00 6c 88

I will need  a0 13 01 89 94 30 00 39 36 30 36 31 37 36 31 35 32 00 00 6c 88

This is my connection

var serial = new SerialPort(me.path, {
      disconnectedCallback : function(){
      },
      baudrate: 115200
    }, false);

**Comment by masnatacion** [comment]
Resolved

**Comment by roryovercast** [comment]
I think I'm having a similar issue. What was the fix?

**Comment by jacobrosenthal** [comment]
There is no guarantee to how data is emitted. Use a parser to only be notified when your delimiter is found (newline?) or use an array or something to buffer data i your handler
