### ISSUE TITLE
Not receiving any data

### ISSUE THREAD

**Issue by untitledlt** [voodootikigod/node-serialport#568]
I am using the same code as in example:

```javascript
serialPort.on("open", function () {
  console.log('open');
  serialPort.on('data', function(data) {
    console.log('data received: ' + data);
  });
});
```

I know that data is received on serial port because I can see with `cat /dev/rfcomm0`
but callback on `serialPort.on('data', function(data) { ... })` is never triggered.

Node v0.12.3
Ubuntu 14.04

**Comment by jacobrosenthal** [comment]
Im presuming you got this figured out?

**Comment by untitledlt** [comment]
Yes, I did. There was an issue with some crashed process which was locking out serial port. Reboot solved it.

**Comment by jacobrosenthal** [comment]
Happy to hear that. You can occasionally get some more eyes on issues by idling in the gitter, too https://gitter.im/voodootikigod/node-serialport
