### ISSUE TITLE
Application aborted without errors.

### ISSUE THREAD

**Issue by luizlago** [voodootikigod/node-serialport#609]
I use serialport for gcode injection on my 3dprinter. In nodejs 0.12.7 everything works well, but node 4.x in random moment my app abort without any error. I disabled the serialport and nothing aborted. When I enable the serialport the problem appears.

In the screenshot ... the printer is warming up to begin printing, the app was aborted. 

![capture](https://cloud.githubusercontent.com/assets/8448291/10456528/47110d9a-7198-11e5-83fe-cffe17892a20.PNG)

Anybody know whats happening? How appear any error?

**Comment by jacobrosenthal** [comment]
There were (at least) two issues found in the node 4 upgrade that have yet to be corroborated or chased down. Perhaps bit by one of these?
* https://github.com/voodootikigod/node-serialport/issues/578#issuecomment-143591608
with [this test](https://gist.github.com/gnail/a1a2c0d11205c00286ab)
* https://github.com/voodootikigod/node-serialport/issues/578#issuecomment-144756809
with [this test](https://github.com/voodootikigod/node-serialport/pull/600/files)

**Comment by ValentinCupif** [comment]
Same issue on Linux. it comes when i closing COM.

**Comment by nicozhang** [comment]
Same issue. Anyone can solve this problem?

**Comment by luizlago** [comment]
I solved my problem between serialport and electron using this fork ... https://github.com/ddm/node-serialport.

**Comment by jacobrosenthal** [comment]
Can you all try 2.0.4 which has a windows patch that might fix this?
