### ISSUE TITLE
Windows  \\.\COM3: File not found Nodejs 4.2.1

### ISSUE THREAD

**Issue by wizhippo** [voodootikigod/node-serialport#616]
Installing went find with a few warning.  When trying to open the port(does list when enumerating) get file not found error.

You can see the build output with warnings at https://gist.github.com/wizhippo/2e7f3a050b9d1985516d

**Comment by jacobrosenthal** [comment]
Is this still going on? as of 2.0.4 we should have functioning binaries so you shouldnt have to build anymore.

**Comment by wizhippo** [comment]
This happens when you try using it with electron.  Need to be ablte to tell node-pre-gyp to build against it instead of node.
