### ISSUE TITLE
Installation now requires git because of `jacobrosenthal/node-pre-gyp-github` dependency

### ISSUE THREAD

**Issue by brycekahle** [voodootikigod/node-serialport#644]
This creates a much larger barrier to users trying to install our [CLI](https://github.com/spark/particle-cli). Are there plans to incorporate the changes in the jacobrosenthal fork of `node-pre-gyp-github` upstream and get a new version published to npm?

**Comment by deadprogram** [comment]
+1

**Comment by jacobrosenthal** [comment]
Upstreamed with 02de1f6c18b52e6c45f1332e21776662e0b20a9b for 2.0.6 release
