### ISSUE TITLE
My data are broken

### ISSUE THREAD

**Issue by abraxasband** [voodootikigod/node-serialport#659]
SO: Windows10
Hardware: Arduino Mega256
Server: NodeJS

Hi All
My problem is that my data appears divided. 

My arduino code is simple

Serial.print("Hola");
delay(1000);

My code in Node 
![prueba](https://cloud.githubusercontent.com/assets/13739661/12223986/b40f54e8-b7c4-11e5-86ea-1038e7be1982.png)

But my data ought to be only "Hola" and the result is this

![prueba2](https://cloud.githubusercontent.com/assets/13739661/12224018/5f0226d2-b7c5-11e5-8734-316adfe3033b.png)

I receipt data, but for some reason, they are cut.

any ideas?

Thanks!

**Comment by jacobrosenthal** [comment]
Serial data is delivered at its convenience. You need collect the results into a string or a buffer and sort through.  Or you can use the inbuilt parser to parse for a delimeter of your choice. You have commented out a readline parser which will wait to deliver your string until it finds a newline.

**Comment by abraxasband** [comment]
Thanks Jacob Rosenthal!
