### ISSUE TITLE
Fails to install on macbook

### ISSUE THREAD

**Issue by gravity-addiction** [voodootikigod/node-serialport#748]
Will not install on macbook

node: 5.6.0
npm: 3.8.6
15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

> serialport@1.5.0 install /usr/local/lib/node_modules/pinoccio/node_modules/serialport
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many
      arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~

**Comment by fivdi** [comment]
serialport v1.5.0 is fairly old and can't be installed with Node.js v5.6.0. For Node.js v4 or higher serialport v2 or higher is required.
